---
version: "3.4"
services:
  fhir:
    # expose HAPI to internet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fhir-${COMPOSE_PROJECT_NAME}.rule=Host(`fhir.${BASE_DOMAIN:-localtest.me}`)"
      - "traefik.http.routers.fhir-${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.fhir-${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.fhir-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt"

      # Hapi does not EXPOSE the ports it listens on, requiring explicit traefik configuration
      - traefik.http.services.fhir-${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8080
    networks:
      - ingress
  requestbin:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.requestbin-${COMPOSE_PROJECT_NAME}.rule=Host(`requestbin.${BASE_DOMAIN:-localtest.me}`)"
      - "traefik.http.routers.requestbin-${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.requestbin-${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.requestbin-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt"
    networks:
      - ingress

networks:
  # ingress network
  ingress:
    external: true
    name: external_web
