---
version: "3.4"
services:
  fhir:
    image: hapiproject/hapi:${FHIR_IMAGE_TAG:-v5.5.1}
    environment:
      SPRING_CONFIG_LOCATION: file:///opt/application.yaml
      spring.datasource.url: jdbc:postgresql://db:5432/hapifhir
      spring.datasource.username: hapifhir
      spring.datasource.password: hapifhir
      spring.datasource.driverClassName: org.postgresql.Driver
      spring.jpa.hibernate.dialect: org.hibernate.dialect.PostgreSQL94Dialect

    volumes:
      - "./config/hapi/application.yaml:/opt/application.yaml:ro"
    depends_on:
      - db
    networks:
      - internal

  db:
    image: postgres:${POSTGRES_IMAGE_TAG:-15}
    environment:
      POSTGRES_DB: hapifhir
      POSTGRES_USER: hapifhir
      POSTGRES_PASSWORD: hapifhir
    volumes:
      - source: postgres-data
        target: /var/lib/postgresql/data
        type: volume
    networks:
      - internal
networks:
  # internal network for backing services
  internal:

volumes:
    postgres-data: {}
